bedfile: refs/Mito_sync_cons05.bed
reference: refs/Mito_sync_cons05.fasta
prim_fw: refs/microhap_pr_fwd.min_overlap.fasta
prim_rv: refs/microhap_pr_rv.min_overlap.fasta
similarity_comparison: refs/ORIGINAL_Spec2-1638-1893.fasta
filtering_criteria: {
    "conservative": {
        "cnb": ">= 3.5",
        "nc": " >= 0.2",
        "align_score": ">= 15",
    },
    "sensitive": {
        "cnb": "> 0.5",
        "nc": " > 0",
        "align_score": "> 0",
    }
  }
min_reads_consideration: {
    "conservative": 2,
    "sensitive": 1,
}