bedfile: refs/model/mit_cons.bed
reference: refs/mit_cons.fasta
prim_fw: refs/microhap_pr_fwd.min_overlap.fasta
prim_rv: refs/microhap_pr_rv.min_overlap.fasta
similarity_comparison: refs/ORIGINAL_Spec2-1638-1893.fasta
filtering_criteria: {
    "conservative": {
        "cnb": ">= 3.5",
        "nc": " >= 0.2",
        "pa": ">= 15",
        "ensemble": ">0"
    },
    "sensitive": {
        "cnb": "> 0.5",
        "nc": " > 0",
        "pa": "> 0",
        "ensemble": ">0"
    }
  }
min_reads_consideration: {
    "conservative": 2,
    "sensitive": 1,
}